CREATE TABLE auth.users (
    instance_id UUID NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    id UUID PRIMARY KEY,
    aud VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    encrypted_password TEXT,
    email_confirmed_at TIMESTAMP,
    invited_at TIMESTAMP,
    confirmation_token TEXT,
    confirmation_sent_at TIMESTAMP,
    recovery_token TEXT,
    recovery_sent_at TIMESTAMP,
    email_change_token_new TEXT,
    email_change TEXT,
    email_change_sent_at TIMESTAMP,
    last_sign_in_at TIMESTAMP,
    raw_app_meta_data JSONB,
    raw_user_meta_data JSONB,
    is_super_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),
    phone VARCHAR(20),
    phone_confirmed_at TIMESTAMP,
    phone_change TEXT,
    phone_change_token TEXT,
    phone_change_sent_at TIMESTAMP,
    confirmed_at TIMESTAMP,
    email_change_token_current TEXT,
    email_change_confirm_status VARCHAR(10),
    banned_until TIMESTAMP,
    reauthentication_token TEXT,
    reauthentication_sent_at TIMESTAMP,
    is_sso_user BOOLEAN DEFAULT false,
    deleted_at TIMESTAMP,
    is_anonymous BOOLEAN DEFAULT false
);
